export const driverCopy = {
  login: {
    title: 'Ingreso conductor',
    subtitle:
      'Tu empresa creó esta cuenta. Ingresa con la cédula y el PIN que te enviaron por SMS.',
    nationalIdLabel: 'Cédula',
    nationalIdPlaceholder: 'Sin puntos ni espacios',
    pinHelper: 'Son 4 dígitos.',
    pinLabel: 'PIN',
    submit: 'Iniciar turno',
    verifying: 'Verificando…',
    offline: 'Sin conexión · no se puede verificar ahora.',
    offlineHint: 'Sin conexión, no se puede verificar ahora',
    credentialsFallback: 'Cédula o PIN incorrectos.',
    blockedTitle: 'Demasiados intentos',
    blockedKnown: (remaining: string) =>
      `Por seguridad, espera ${remaining} para volver a intentar. Si no recuerdas tu PIN, contacta a tu empresa.`,
    blockedUnknown:
      'Por seguridad, espera unos minutos para volver a intentar. Si no recuerdas tu PIN, contacta a tu empresa.',
    suspendedTitle: 'No puedes ingresar ahora',
    suspendedFallback:
      'Tu empresa suspendió tu acceso. Contacta a tu empresa para más información.',
    suspendedBack: 'Probar con otra cuenta',
    footer: 'La cuenta la crea tu empresa. Si no la tienes, contáctala directamente.',
  },
  home: {
    onShiftEyebrow: 'En turno',
    offShiftEyebrow: 'Fuera de turno',
    waitingTitle: 'Esperando solicitudes',
    waitingBody: 'Sigues visible para los pasajeros.',
    offShiftTitle: 'Estás fuera de turno',
    offShiftBody: 'Actívalo para empezar a recibir solicitudes cercanas.',
    activateShift: 'Activar turno',
    endShift: 'Terminar turno',
    shiftBusyOn: 'Activando turno…',
    shiftBusyOff: 'Actualizando turno…',
    shiftOnHint: 'Recibiendo solicitudes cercanas.',
    noVehicle: 'No tienes un vehículo vinculado. Contacta al administrador.',
    nearbyTitle: 'Solicitudes cercanas',
    seeAll: (count: number) => `Ver todas (${count})`,
    emptyTitle: 'Sin solicitudes cercanas por ahora',
    emptyBody: 'Sigues visible para los pasajeros.',
    homeLoadError: 'No pudimos cargar tu estado de turno',
    offersLoadError: 'No pudimos cargar tus solicitudes',
    nearest: 'Más cercana',
    rulesTrigger: '¿Cómo se asignan los viajes?',
    rulesTitle: 'Reglas de asignación',
    rulesBody: (radiusKm: number, timeoutSec: number) =>
      `Mostradas por cercanía · radio ${radiusKm} km · ${timeoutSec} s para responder`,
    cashBanner: (count: number) =>
      count === 1
        ? 'Tienes 1 viaje sin confirmar el cobro.'
        : `Tienes ${count} viajes sin confirmar el cobro.`,
    accountOpen: 'Mi cuenta',
  },
  offer: {
    title: 'Nueva solicitud',
    banner: (distanceM: number, neighborhood: string) =>
      `Recoger a ${distanceM} m · ${neighborhood}`,
    bannerAnnouncement: (distanceM: number, seconds: number) =>
      `Nueva solicitud. ${distanceM} metros. ${seconds} segundos para responder.`,
    detailEyebrow: 'Nueva solicitud',
    fareCaption: 'Tarifa de este viaje',
    pickupLabel: 'Recoger en',
    pickupValue: (address: string, distanceM: number) => `${address} · a ${distanceM} m`,
    destinationLabel: 'Destino',
    accept: 'Aceptar',
    accepting: 'Aceptando…',
    reject: 'Rechazar',
    rejecting: 'Rechazando…',
    acceptLabel: 'Aceptar solicitud',
    rejectLabel: 'Rechazar solicitud',
    backNotice: 'Para rechazar, pulsa Rechazar',
    mountAnnouncement: (seconds: number) => `Nueva solicitud, quedan ${seconds} segundos.`,
    accepted: (name: string | null) => (name ? `¡Aceptada! Vas hacia ${name}.` : '¡Aceptada!'),
    rejected: 'Rechazada · buscando otro conductor.',
    expired: 'Se agotó el tiempo · pasando al siguiente conductor.',
    takenByOther: 'Esta solicitud ya fue tomada · sigues en turno, te avisaremos de la próxima.',
    offlineResponse: 'Sin conexión · no pudimos enviar tu respuesta.',
    genericResponse: 'No pudimos procesar tu respuesta.',
    notFoundTitle: 'No encontramos esta solicitud',
    notFoundBody: 'Puede que ya haya expirado o que la lista se haya actualizado.',
    backToList: 'Volver a la lista',
    loadError: 'No pudimos cargar esta solicitud',
    loadingLabel: 'Cargando la solicitud…',
  },
  requests: {
    title: 'Solicitudes activas',
    hint: 'Toca una solicitud para ver el detalle y aceptarla.',
    offline: 'Sin conexión · reintentando…',
    updatedAgo: (seconds: number) => ` Actualizado hace ${seconds} s.`,
    emptyTitle: 'Sin solicitudes cercanas',
    emptyBody:
      'Te avisaremos apenas llegue una solicitud cerca de ti. Sigues visible para los pasajeros.',
    reviewShift: 'Revisar mi turno y zona',
    loadingAnnouncement: 'Cargando solicitudes cercanas',
  },
  trip: {
    title: 'Viaje',
    enRouteTitle: (name: string | null) =>
      name ? `En camino a recoger a ${name}` : 'En camino a recoger al pasajero',
    waitingTitle: (name: string | null) => (name ? `Esperando a ${name}` : 'Esperando al pasajero'),
    inProgressTitle: 'Viaje en curso',
    steps: { enRoute: 'En camino', waiting: 'Esperando', inProgress: 'En viaje' },
    pickupLabel: 'Recoger en',
    destinationLabel: 'Destino',
    arrivedChip: 'Llegaste · cortesía en curso',
    startEnRoute: 'Voy en camino',
    arrived: 'Llegué al punto de recogida',
    startTrip: 'Inicié el viaje',
    finishTrip: 'Finalizar viaje',
    directionsToPickup: 'Cómo llegar al punto de recogida',
    directionsToDropoff: 'Cómo llegar al destino',
    directionsError: 'No pudimos abrir la aplicación de mapas.',
    moreOptions: 'Más opciones',
    alreadyStarted: 'Ya inició el viaje',
    cancelTrip: 'Cancelar viaje',
    noShow: 'Pasajero no se presentó',
    noShowIn: (mmss: string) => `Pasajero no se presentó (disponible en ${mmss})`,
    actionOffline: 'Sin conexión · no pudimos enviar tu acción.',
    actionGeneric: 'No pudimos procesar la acción.',
    loadError: 'No pudimos cargar tu viaje',
    loadingLabel: 'Cargando tu viaje…',
    startedSheetTitle: '¿El viaje ya inició?',
    startedSheetBody:
      'Se registrará como en curso desde ahora. Úsalo solo si ya recogiste al pasajero.',
    startedSheetConfirm: 'Sí, ya inició',
    startedSheetKeep: 'Todavía no',
    startedSheetLoading: 'Registrando…',
    closedFinished: 'Viaje finalizado',
    closedNoShow: 'Viaje cerrado',
    closedCancelled: 'Viaje cancelado',
    toastFinishedCash: 'Viaje finalizado. Cobro confirmado.',
    toastFinished: 'Viaje finalizado.',
    toastNoShow: 'Viaje cerrado · el pasajero no se presentó.',
    toastCancelled: 'Viaje cancelado.',
    passenger: 'Pasajero',
  },
  cash: {
    title: 'Cobros pendientes',
    headerEyebrow: 'Por confirmar',
    headerCaption: (count: number) =>
      count === 1 ? '1 viaje sin confirmar' : `${count} viajes sin confirmar`,
    offline: 'Sin conexión · no se puede confirmar ahora.',
    loadError: 'No pudimos cargar tus cobros pendientes',
    emptyTitle: 'Todo al día',
    emptyBody: 'No tienes viajes pendientes de confirmar cobro.',
    confirm: 'Cobré en efectivo',
    confirming: 'Confirmando…',
    confirmed: 'Cobro confirmado',
    rowError: 'No pudimos confirmar este cobro.',
  },
  issues: {
    permissionDenied: 'Necesitamos tu ubicación para activar el turno.',
    permissionDeniedAction: 'Cómo habilitarlo',
    gpsDisabled: 'Activa la ubicación de tu teléfono para poder recibir solicitudes.',
    gpsDisabledAction: 'Abrir ajustes',
    offline: 'Sin conexión · no pudimos activar tu turno.',
    serverError: 'No pudimos activar tu turno.',
    retry: 'Reintentar',
    blockedByTrip:
      'No puedes salir de turno con un viaje en curso. Finalízalo o cancélalo primero.',
    locationPermission: 'Revisa el permiso de ubicación: no estás recibiendo solicitudes.',
  },
} as const;
