import { DRIVER_LOCATION_RETENTION_MAX_HOURS, DRIVER_PIN_LENGTH } from '@voyyaa/shared';

export const driverCopy = {
  login: {
    title: 'Ingreso conductor',
    subtitle:
      'Tu empresa creó esta cuenta. Ingresa con la cédula y el PIN que te enviaron por SMS.',
    nationalIdLabel: 'Cédula',
    nationalIdPlaceholder: 'Sin puntos ni espacios',
    pinHelper: `Son ${DRIVER_PIN_LENGTH} números.`,
    pinLabel: 'PIN',
    submit: 'Iniciar turno',
    verifying: 'Verificando…',
    offline: 'Sin conexión · no se puede verificar ahora.',
    offlineHint: 'Sin conexión, no se puede verificar ahora',
    credentialsFallback: 'Cédula o PIN incorrectos.',
    blockedTitle: 'Demasiados intentos',
    blockedKnown: (remaining: string) =>
      `Por seguridad, espera ${remaining} para volver a intentar. Si no recuerdas tu PIN, contacta a tu empresa.`,
    blockedUnknown:
      'Por seguridad, espera unos minutos para volver a intentar. Si no recuerdas tu PIN, contacta a tu empresa.',
    suspendedTitle: 'No puedes ingresar ahora',
    suspendedFallback:
      'Tu empresa suspendió tu acceso. Contacta a tu empresa para más información.',
    suspendedBack: 'Probar con otra cuenta',
    footer: 'La cuenta la crea tu empresa. Si no la tienes, contáctala directamente.',
  },
  createPin: {
    title: 'Crea tu PIN',
    titleAccent: 'tu PIN',
    body: `Con el PIN del mensaje entraste una vez. Ahora crea uno solo tuyo, de ${DRIVER_PIN_LENGTH} números.`,
    currentLabel: 'PIN que recibiste',
    currentHint: 'Escribe el PIN que te llegó por mensaje',
    nextLabel: 'PIN nuevo',
    nextHelper: `${DRIVER_PIN_LENGTH} números. Evita 123456, 111111 y tu cédula.`,
    nextHint: `Escribe ${DRIVER_PIN_LENGTH} números`,
    confirmLabel: 'Repite tu PIN nuevo',
    confirmHint: 'Escribe otra vez el PIN nuevo',
    ruleLength: `${DRIVER_PIN_LENGTH} números`,
    rulePattern: 'No es una secuencia ni se repite (123456, 111111, 121212)',
    ruleMet: 'Cumple',
    ruleNotMet: 'Pendiente',
    mismatch: 'Los PIN no coinciden',
    tooWeak: 'Elige un PIN que no salga de tu cédula ni de tu teléfono',
    wrongCurrent: 'Ese no es el PIN que recibiste. Revisa el mensaje y vuelve a intentar.',
    submit: 'Guardar mi PIN',
    saving: 'Guardando…',
    submitHint: 'Completa los tres campos con PIN que coincidan para poder guardar',
    submitHintShort: 'Completa los campos para poder guardar',
    offlineBanner: 'Sin conexión · reintentando…',
    offlineHint: 'Sin conexión, no se puede guardar ahora',
    offlineFailed: 'Sin conexión: tu PIN no se cambió. Sigues con el PIN que recibiste.',
    serverError: 'No pudimos guardar tu PIN. Inténtalo de nuevo.',
    retry: 'Reintentar',
    blockedTitle: 'Demasiados intentos',
    blockedKnown: (remaining: string) => `Intenta de nuevo en ${remaining}.`,
    blockedUnknown: 'Intenta de nuevo en unos minutos.',
    successTitle: 'Listo, tu PIN quedó guardado',
    successBody: 'Úsalo la próxima vez que entres. Las demás sesiones se cerraron.',
    expiredTitle: 'Tu PIN temporal venció',
    expiredBody: 'Pide a tu empresa que te lo reenvíe. Te llegará un mensaje nuevo.',
    expiredAction: 'Volver al inicio',
    logout: 'Cerrar sesión',
    logoutConfirmTitle: '¿Cerrar sesión en este teléfono?',
    logoutConfirmBody: 'Cuando vuelvas a entrar tendrás que crear tu PIN.',
    loggingOut: 'Cerrando sesión…',
    cancel: 'Cancelar',
    showPin: 'Mostrar PIN',
    hidePin: 'Ocultar PIN',
  },
  consentNotice: {
    primaryShift: 'Acepto, activar turno',
    primaryAccept: 'Acepto',
    secondary: 'Ahora no',
    primaryRead: 'Entendido',
    saving: 'Guardando…',
    retry: 'Reintentar',
    errorLabel: 'No pudimos guardar tu aceptación',
    errorValue: 'Revisa tu conexión e inténtalo de nuevo.',
    factsHeading: 'Lo esencial, antes de aceptar',
    facts: [
      {
        label: 'Quién te ve y cuándo',
        value:
          'El pasajero de cada viaje que aceptas ve dónde estás, desde que aceptas hasta que inicias el viaje. Tu empresa no ve dónde estás.',
      },
      {
        label: 'Aunque VoyYa no esté en pantalla',
        value:
          'En Android sigue funcionando con una notificación visible de VoyYa. En iPhone solo comparte con VoyYa en pantalla.',
      },
      {
        label: 'No guardamos tu recorrido',
        value: 'Guardamos solo tu última ubicación, no el camino que haces.',
      },
      {
        label: 'Google Maps y Waze',
        value:
          'Reciben las coordenadas del punto de recogida o del destino cuando tocas el botón de ruta. No reciben tu nombre ni el del pasajero.',
      },
    ],
  },
  privacy: {
    title: 'Privacidad de mi ubicación',
    statusLabel: (state: string) => `Estado: ${state}`,
    sharing: 'Compartiendo',
    newNotice: 'Aviso nuevo',
    revoked: 'Sin compartir',
    none: 'Sin aceptar',
    sharingBody: (date: string) => `Aceptaste el aviso el ${date}.`,
    sharingVersion: (version: string) => `Versión del aviso: ${version}`,
    newNoticeBody: 'Cambiamos el aviso. Léelo y acéptalo para seguir.',
    revokedBody: (date: string) => `Dejaste de compartir tu ubicación el ${date}.`,
    noneBody: 'Todavía no aceptaste el aviso de ubicación.',
    dateUnknown: 'una fecha que no tenemos registrada',
    readAndAccept: 'Leer y aceptar',
    shareAgain: 'Volver a compartir',
    readNotice: 'Leer el aviso',
    readFull: 'Leer el aviso completo',
    loadError: 'No pudimos consultar tu autorización.',
    offlineStatus: 'Sin conexión: no podemos mostrar tu estado ahora.',
    offlineHint: 'Sin conexión, no se puede cambiar ahora',
    permissionTitle: 'Quitaste el permiso en los ajustes',
    permissionBody: `Quitaste el permiso en los ajustes del teléfono, así que no recibirás viajes. La última ubicación guardada se borra a más tardar ${DRIVER_LOCATION_RETENTION_MAX_HOURS} horas después de tu último reporte. Para borrarla ya, usa «Dejar de compartir mi ubicación».`,
    openSettings: 'Abrir ajustes',
    revoke: 'Dejar de compartir mi ubicación',
    rights: (email: string) => `¿Quieres ejercer tus derechos? Escríbenos a ${email}.`,
    mailAction: 'Escribir al correo de privacidad',
    mailHint: 'Abre tu correo',
    revokeTitle: '¿Dejar de compartir tu ubicación?',
    revokeLines: [
      'Saldrás de turno y no recibirás viajes.',
      'Borraremos tu última ubicación ahora mismo.',
      'Para volver a turno tendrás que aceptar el aviso otra vez.',
    ],
    revokeLinesActiveTrip: [
      'Tu viaje sigue: termínalo con normalidad.',
      'Borraremos tu última ubicación ahora mismo y no la reportaremos más.',
      'Saldrás de turno cuando termines el viaje.',
    ],
    revokeConfirm: 'Dejar de compartir',
    revoking: 'Borrando tu ubicación…',
    revokeKeep: 'Cancelar',
    revokeOffline: 'Sin conexión: no pudimos borrar tu ubicación todavía. Tu turno sigue abierto.',
    revokeError:
      'No pudimos completar el cambio. Tu ubicación todavía no se borró. Inténtalo de nuevo.',
    revokeRetry: 'Reintentar',
    toastRevoked: 'Listo. Borramos tu última ubicación.',
    toastRevokedActiveTrip:
      'Listo. Borramos tu última ubicación. Saldrás de turno al terminar tu viaje.',
  },
  home: {
    onShiftEyebrow: 'En turno',
    offShiftEyebrow: 'Fuera de turno',
    waitingTitle: 'Esperando solicitudes',
    waitingBody: 'Sigues visible para los pasajeros.',
    offShiftTitle: 'Estás fuera de turno',
    offShiftBody: 'Actívalo para empezar a recibir solicitudes cercanas.',
    activateShift: 'Activar turno',
    endShift: 'Terminar turno',
    shiftBusyOn: 'Activando turno…',
    shiftBusyOff: 'Actualizando turno…',
    shiftOnHint: 'Recibiendo solicitudes cercanas.',
    noVehicle: 'No tienes un vehículo vinculado. Contacta al administrador.',
    nearbyTitle: 'Solicitudes cercanas',
    seeAll: (count: number) => `Ver todas (${count})`,
    emptyTitle: 'Sin solicitudes cercanas por ahora',
    emptyBody: 'Sigues visible para los pasajeros.',
    homeLoadError: 'No pudimos cargar tu estado de turno',
    offersLoadError: 'No pudimos cargar tus solicitudes',
    nearest: 'Más cercana',
    rulesTrigger: '¿Cómo se asignan los viajes?',
    rulesTitle: 'Reglas de asignación',
    rulesBody: (radiusKm: number, timeoutSec: number) =>
      `Mostradas por cercanía · radio ${radiusKm} km · ${timeoutSec} s para responder`,
    cashBanner: (count: number) =>
      count === 1
        ? 'Tienes 1 viaje sin confirmar el cobro.'
        : `Tienes ${count} viajes sin confirmar el cobro.`,
    accountOpen: 'Mi cuenta',
  },
  offer: {
    title: 'Nueva solicitud',
    banner: (distanceM: number, neighborhood: string) =>
      `Recoger a ${distanceM} m · ${neighborhood}`,
    bannerAnnouncement: (distanceM: number, seconds: number) =>
      `Nueva solicitud. ${distanceM} metros. ${seconds} segundos para responder.`,
    detailEyebrow: 'Nueva solicitud',
    fareCaption: 'Tarifa de este viaje',
    pickupLabel: 'Recoger en',
    pickupValue: (address: string, distanceM: number) => `${address} · a ${distanceM} m`,
    destinationLabel: 'Destino',
    accept: 'Aceptar',
    accepting: 'Aceptando…',
    reject: 'Rechazar',
    rejecting: 'Rechazando…',
    acceptLabel: 'Aceptar solicitud',
    rejectLabel: 'Rechazar solicitud',
    backNotice: 'Para rechazar, pulsa Rechazar',
    mountAnnouncement: (seconds: number) => `Nueva solicitud, quedan ${seconds} segundos.`,
    accepted: (name: string | null) => (name ? `¡Aceptada! Vas hacia ${name}.` : '¡Aceptada!'),
    rejected: 'Rechazada · buscando otro conductor.',
    expired: 'Se agotó el tiempo · pasando al siguiente conductor.',
    takenByOther: 'Esta solicitud ya fue tomada · sigues en turno, te avisaremos de la próxima.',
    offlineResponse: 'Sin conexión · no pudimos enviar tu respuesta.',
    genericResponse: 'No pudimos procesar tu respuesta.',
    notFoundTitle: 'No encontramos esta solicitud',
    notFoundBody: 'Puede que ya haya expirado o que la lista se haya actualizado.',
    backToList: 'Volver a la lista',
    loadError: 'No pudimos cargar esta solicitud',
    loadingLabel: 'Cargando la solicitud…',
  },
  requests: {
    title: 'Solicitudes activas',
    hint: 'Toca una solicitud para ver el detalle y aceptarla.',
    offline: 'Sin conexión · reintentando…',
    updatedAgo: (seconds: number) => ` Actualizado hace ${seconds} s.`,
    emptyTitle: 'Sin solicitudes cercanas',
    emptyBody:
      'Te avisaremos apenas llegue una solicitud cerca de ti. Sigues visible para los pasajeros.',
    reviewShift: 'Revisar mi turno y zona',
    loadingAnnouncement: 'Cargando solicitudes cercanas',
  },
  trip: {
    title: 'Viaje',
    enRouteTitle: (name: string | null) =>
      name ? `En camino a recoger a ${name}` : 'En camino a recoger al pasajero',
    waitingTitle: (name: string | null) => (name ? `Esperando a ${name}` : 'Esperando al pasajero'),
    inProgressTitle: 'Viaje en curso',
    steps: { enRoute: 'En camino', waiting: 'Esperando', inProgress: 'En viaje' },
    pickupLabel: 'Recoger en',
    destinationLabel: 'Destino',
    arrivedChip: 'Llegaste · cortesía en curso',
    startEnRoute: 'Voy en camino',
    arrived: 'Llegué al punto de recogida',
    startTrip: 'Iniciar viaje',
    startTripHint: 'Te pedirá el código del pasajero.',
    finishTrip: 'Finalizar viaje',
    moreOptions: 'Más opciones',
    alreadyStarted: 'Ya inició el viaje',
    cancelTrip: 'Cancelar viaje',
    noShow: 'Pasajero no se presentó',
    noShowIn: (mmss: string) => `Pasajero no se presentó (disponible en ${mmss})`,
    actionOffline: 'Sin conexión · no pudimos enviar tu acción.',
    actionGeneric: 'No pudimos procesar la acción.',
    loadError: 'No pudimos cargar tu viaje',
    loadingLabel: 'Cargando tu viaje…',
    startedSheetTitle: '¿El viaje ya inició?',
    startedSheetBody:
      'Se registrará como en curso desde ahora. Úsalo solo si ya recogiste al pasajero.',
    startedSheetConfirm: 'Sí, ya inició',
    startedSheetKeep: 'Todavía no',
    startedSheetLoading: 'Registrando…',
    closedFinished: 'Viaje finalizado',
    closedNoShow: 'Viaje cerrado',
    closedCancelled: 'Viaje cancelado',
    toastFinishedCash: 'Viaje finalizado. Cobro confirmado.',
    toastFinished: 'Viaje finalizado.',
    toastNoShow: 'Viaje cerrado · el pasajero no se presentó.',
    toastCancelled: 'Viaje cancelado.',
    passenger: 'Pasajero',
  },
  startCode: {
    sheetTitle: 'Código de inicio',
    sheetBody: 'Pídele al pasajero su código de 4 números y escríbelo aquí.',
    helper: 'Está en la app del pasajero, en la tarjeta de su viaje.',
    inputLabel: 'Código de inicio, 4 números',
    confirm: 'Iniciar viaje',
    confirmDisabledHint: 'Escribe los 4 números para continuar',
    verifying: 'Verificando…',
    back: 'Volver',
    priorAttempts: (n: number) =>
      n === 1
        ? 'Ya hubo intentos fallidos. Te queda 1 intento.'
        : `Ya hubo intentos fallidos. Te quedan ${n} intentos.`,
    invalid: (n: number) => `Código incorrecto. Te quedan ${n} intentos.`,
    invalidLast: 'Código incorrecto. Último intento.',
    invalidUnknown: 'Código incorrecto. Revisa los números e inténtalo de nuevo.',
    lastAttemptWarning: 'Último intento. Si fallas, el inicio de este viaje se bloquea.',
    offline: 'Sin conexión. Para iniciar necesitamos validar el código en el servidor.',
    uncertain: 'No pudimos confirmar el resultado. Revisando tu viaje…',
    notSent: 'No se envió el código. Revisa tu conexión e inténtalo de nuevo.',
    rateLimited: 'Demasiados intentos seguidos. Espera unos segundos e inténtalo de nuevo.',
    tripChanged: 'El viaje cambió. Actualizamos tu pantalla.',
    server: 'No pudimos procesar la acción.',
    success: 'Código correcto. Viaje iniciado.',
    alreadyStartedTitle: '¿El viaje ya inició?',
    alreadyStartedBody: 'Para registrar el inicio, escribe el código de 4 números del pasajero.',
    alreadyStartedConfirm: 'Registrar inicio',
    alreadyStartedKeep: 'Todavía no',
  },
  blocked: {
    title: 'El inicio de este viaje quedó bloqueado',
    body: 'No pudimos verificar el código después de 5 intentos. Por seguridad, no se puede volver a intentar.',
    heading: '¿Qué puedes hacer?',
    callPassenger: 'Llamar al pasajero',
    noPhone: 'No hay teléfono del pasajero disponible.',
    needArrival: 'Marca que llegaste para que empiece la cortesía de espera.',
    advice:
      'Si el pasajero está contigo, cancela este viaje y pídele que vuelva a solicitar un taxi.',
    announcement: 'El inicio de este viaje quedó bloqueado. Revisa las opciones.',
  },
  route: {
    toPickup: 'Abrir ruta al punto de recogida',
    toDropoff: 'Abrir ruta al destino',
    pickupTarget: 'punto de recogida',
    dropoffTarget: 'destino',
    opensIn: (app: string) => `Se abrirá en ${app}`,
    accessibility: (target: string, app: string | null) =>
      `Abrir ruta al ${target} en ${app ?? 'una app de navegación'}`,
    changeApp: 'Cambiar app',
    sheetTitle: '¿Con qué app abrimos tu ruta?',
    sheetBody: 'La recordaremos para la próxima vez. Puedes cambiarla cuando quieras.',
    failedTitle: 'No pudimos abrir una app de mapas',
    failedBody: 'Puedes escribir estas coordenadas en tu app de navegación:',
    failedDone: 'Entendido',
    apps: { google_maps: 'Google Maps', waze: 'Waze' },
  },
  sharing: {
    active: 'Compartiendo tu ubicación con el pasajero',
    noGps: 'Sin señal GPS · tu pasajero ve tu última ubicación',
    offline: 'Sin conexión · tu pasajero ve tu última ubicación',
    consentRequired: 'Acepta el aviso nuevo para que tu pasajero te vea.',
    consentAction: 'Leer y aceptar',
    consentDone: 'Listo. Tu pasajero ya puede verte.',
    stoppedToast: 'Viaje iniciado. Dejamos de compartir tu ubicación con el pasajero.',
    preciseNeeded: 'Activa la ubicación precisa para que tu pasajero te vea.',
    preciseAction: 'Ir a ajustes',
    notificationsOff: 'Activa las notificaciones para ver el aviso de ubicación compartida.',
    notificationsAction: 'Activar',
    capReached: 'Se detuvo el seguimiento después de 90 min.',
    capAction: 'Volver a compartir',
    resuming: 'Verificando…',
    resumeOffline: 'Sin conexión. No pudimos reanudar el seguimiento.',
    resumeFailed: 'No pudimos reanudar el seguimiento.',
    iosOnlyForeground: 'Solo compartimos tu ubicación mientras VoyYa esté en pantalla.',
    notificationTitle: 'VoyYa está compartiendo tu ubicación con el pasajero',
    notificationBody: 'Se detiene cuando inicias el viaje. Toca para volver a VoyYa.',
  },
  disclosure: {
    title: 'Tu pasajero te verá venir',
    intro:
      'Desde que aceptas un viaje hasta que lo inicias, VoyYa comparte tu ubicación con el pasajero de ese viaje, aunque VoyYa no esté en pantalla.',
    bullets: [
      'Mientras tanto verás una notificación de VoyYa.',
      'Al iniciar el viaje, se detiene.',
      'No guardamos tu recorrido: solo tu última ubicación.',
      'Si abres Google Maps o Waze con el botón de ruta, ellos reciben las coordenadas del punto.',
    ],
    iosNote: 'En iPhone solo compartimos tu ubicación mientras VoyYa esté en pantalla.',
    fullNotice: 'Ver aviso completo',
    ok: 'Entendido',
  },
  cash: {
    title: 'Cobros pendientes',
    headerEyebrow: 'Por confirmar',
    headerCaption: (count: number) =>
      count === 1 ? '1 viaje sin confirmar' : `${count} viajes sin confirmar`,
    offline: 'Sin conexión · no se puede confirmar ahora.',
    loadError: 'No pudimos cargar tus cobros pendientes',
    emptyTitle: 'Todo al día',
    emptyBody: 'No tienes viajes pendientes de confirmar cobro.',
    confirm: 'Cobré en efectivo',
    confirming: 'Confirmando…',
    confirmed: 'Cobro confirmado',
    rowError: 'No pudimos confirmar este cobro.',
    addressRemoved: 'Dirección eliminada por política de retención.',
  },
  issues: {
    permissionDenied: 'Necesitamos tu ubicación para activar el turno.',
    permissionDeniedAction: 'Cómo habilitarlo',
    gpsDisabled: 'Activa la ubicación de tu teléfono para poder recibir solicitudes.',
    gpsDisabledAction: 'Abrir ajustes',
    locationTimeout: 'No pudimos obtener tu ubicación a tiempo. Inténtalo de nuevo.',
    offline: 'Sin conexión · no pudimos activar tu turno.',
    serverError: 'No pudimos activar tu turno.',
    retry: 'Reintentar',
    blockedByTrip:
      'No puedes salir de turno con un viaje en curso. Finalízalo o cancélalo primero.',
    locationPermission: 'Revisa el permiso de ubicación: no estás recibiendo solicitudes.',
    consentRequired:
      'Tu autorización de ubicación ya no está vigente. Acepta el aviso de nuevo para seguir en turno.',
    consentRequiredAction: 'Leer y aceptar',
    preciseLocationNeeded: 'Activa la ubicación precisa para que tu pasajero te vea.',
  },
} as const;
