import { formatCOP } from '@voyyaa/ui-mobile';
import { DATA_CONTROLLER, TRIP_COORDINATES_RETENTION_DAYS } from '@voyyaa/shared';
import { FREE_CANCELLATION_WINDOW_MIN } from '../constants/parameters';
import { CAN_PIN_DROP } from '../constants/platform';

export const passengerCopy = {
  auth: {
    heroTitle: 'Tu taxi, sin llamar a nadie.',
    heroAccent: 'sin llamar a nadie.',
    phoneLabel: 'Número de celular',
    phonePlaceholder: '300 123 4567',
    phoneIntro: 'Te enviaremos un código por SMS para confirmar tu número.',
    phoneInvalid: 'Ese número no parece válido. Verifica que sean 10 dígitos de un celular.',
    sendCode: 'Enviar código',
    sending: 'Enviando…',
    offlineSend: 'Sin conexión · no se puede enviar el código ahora.',
    offlineSendHint: 'Sin conexión, no se puede enviar el código ahora',
    rateLimitTitle: 'Ya pediste varios códigos',
    rateLimitWait: (remaining: string): string =>
      `Por seguridad, espera ${remaining} antes de solicitar uno nuevo.`,
    rateLimitWaitUnknown: 'Espera unos minutos antes de intentar de nuevo.',
    otpHeader: 'Verificación',
    otpSentTo: 'Enviamos un código de 4 dígitos a',
    otpAnnounce: (maskedPhone: string): string =>
      `Código enviado a ${maskedPhone}. Ingresa los 4 dígitos.`,
    otpVerifying: 'Verificando código…',
    otpVerifyingAnnounce: 'Verificando código.',
    otpIncorrect: 'Código incorrecto. Inténtalo de nuevo.',
    otpExpired: 'Este código venció. Solicita uno nuevo.',
    otpOffline: 'Sin conexión · no pudimos verificar tu código.',
    otpOfflineAnnounce: 'Sin conexión, no pudimos verificar tu código.',
    otpSuccess: 'Código verificado.',
    otpRetry: 'Reintentar',
    otpResend: 'Reenviar código',
    otpResending: 'Reenviando…',
    otpResendIn: (seconds: number): string => `Reenviar código en ${seconds} s`,
    otpResendAvailable: 'Ya puedes reenviar el código.',
    otpResent: 'Código reenviado.',
    otpRateLimited: (remaining: string): string =>
      `Ya pediste varios códigos · espera ${remaining} antes de pedir otro.`,
    otpRateLimitedUnknown: 'Ya pediste varios códigos · espera unos minutos antes de pedir otro.',
  },
  home: {
    whereTo: '¿A dónde vas?',
    whereToHint: 'Toca para escribir tu destino',
    whereToLabel: '¿A dónde vas? Toca para escribir tu destino',
    placesTitle: 'Lugares de Yarumal',
    originLabel: 'Te recogemos en',
    changeOrigin: 'Cambiar',
    locating: 'Buscando tu ubicación…',
    noOriginTitle: 'Marca dónde te recogemos',
    noOriginBody: CAN_PIN_DROP
      ? 'Puedes pedir tu taxi sin compartir tu ubicación: elige el punto en el mapa o en la lista de lugares.'
      : 'Puedes pedir tu taxi sin compartir tu ubicación: elige el punto en la lista de lugares.',
    pickPoint: 'Marcar mi punto de recogida',
    consentSaveErrorTitle: 'No pudimos registrar tu aceptación',
    consentSaveErrorBody: 'Revisa tu conexión e inténtalo de nuevo, o marca tu punto de recogida.',
    permissionDisabled: 'El permiso está desactivado en los ajustes del teléfono.',
    useMyLocation: 'Usar mi ubicación',
    coverageErrorTitle: 'No pudimos verificar tu zona',
    coverageErrorBody: 'Puedes seguir e intentarlo; te avisaremos si tu viaje no se puede cotizar.',
    offlineNote: 'Sin conexión · algunas acciones no estarán disponibles.',
  },
  destination: {
    header: 'Tu viaje',
    noOriginTitle: 'Aún no tienes un punto de partida',
    noOriginBody: CAN_PIN_DROP
      ? 'Márcalo en el mapa o elige un lugar conocido.'
      : 'Elige un lugar conocido o usa tu ubicación.',
    useMyLocation: 'Usar mi ubicación',
    changeOrigin: 'Cambiar',
    originLabel: 'Origen',
    destinationLabel: 'Destino',
    destinationPlaceholder: 'Escribe tu destino…',
    searchLabel: 'Buscar destino',
    searchPlaceholder: 'Buscar dirección, sitio o referencia',
    placesTitle: 'Lugares de Yarumal',
    emptyTitle: 'No encontramos ese lugar',
    emptyBody: CAN_PIN_DROP ? 'Márcalo en el mapa.' : 'Prueba con otro nombre.',
    pendingLocation: CAN_PIN_DROP
      ? 'Ubicación pendiente de confirmar · márcalo en el mapa'
      : 'Ubicación pendiente de confirmar',
    pendingLabel: (title: string): string =>
      CAN_PIN_DROP
        ? `${title}, ubicación pendiente de confirmar, márcalo en el mapa`
        : `${title}, ubicación pendiente de confirmar`,
    pendingBadge: 'Pendiente',
    pinPoint: 'Punto marcado en el mapa',
    useAsOrigin: 'Usar este punto como origen',
    useAsDestination: 'Usar este punto como destino',
    verifying: 'Verificando…',
    quoting: 'Cotizando…',
    outOfCoverageTitle: 'Fuera de cobertura',
    outOfCoverage: (target: 'origin' | 'destination'): string =>
      target === 'origin'
        ? 'Ese punto de partida está fuera de la zona donde operamos en Yarumal por ahora.'
        : 'Ese destino está fuera de la zona donde operamos en Yarumal por ahora.',
    offlineQuote: 'Sin conexión · no se puede cotizar un destino ahora.',
    quoteErrorTitle: 'No pudimos cotizar tu viaje',
    quoteErrorBody: 'Inténtalo de nuevo en un momento.',
    retry: 'Reintentar',
  },
  confirm: {
    header: 'Confirmar viaje',
    origin: 'Origen',
    destination: 'Destino',
    references: 'Referencias (opcional)',
    pickupReferenceLabel: '¿Alguna referencia para que te encuentren?',
    pickupReferenceAccessibility: 'Referencia para tu punto de recogida, opcional',
    dropoffReferenceLabel: 'Referencia del destino',
    dropoffReferenceAccessibility: 'Referencia para tu destino, opcional',
    fareTitle: 'Tarifa',
    fareClosed: 'Tarifa cerrada · pagas en efectivo al terminar',
    freeCancellation: `Cancelación gratis hasta ${FREE_CANCELLATION_WINDOW_MIN} min después de asignar.`,
    requestTrip: (total: number): string => `Solicitar viaje · ${formatCOP(total)}`,
    requesting: 'Solicitando…',
    requote: 'La tarifa cambió, recotizando…',
    createErrorTitle: 'No pudimos crear tu solicitud',
    createErrorBody: 'Inténtalo de nuevo en un momento.',
    offlineRequest: 'Sin conexión · no se puede solicitar el viaje ahora.',
    offlineRequestHint: 'Sin conexión, no se puede solicitar ahora',
  },
  searching: {
    eyebrow: 'Tu viaje',
    title: 'Buscando tu viaje…',
    matchedTitle: 'Conductor asignado',
    body: 'Estamos contactando a los conductores cercanos.',
    prolongedBody: 'Seguimos buscando el conductor más cercano…',
    matchedBody: 'Te mostramos sus datos ahora.',
    elapsed: (mmss: string): string => `hace ${mmss}`,
    cash: 'Efectivo · tarifa cerrada',
    cancel: 'Cancelar',
    cancelling: 'Cancelando…',
    cancelOfflineHint: 'Sin conexión, no se puede cancelar ahora',
    cancelled: 'Solicitud cancelada.',
    notFoundTitle: 'No encontramos tu solicitud',
    backHome: 'Volver al inicio',
    statusErrorTitle: 'No pudimos ver el estado de tu viaje',
    noDriverTitle: 'No hay taxis disponibles ahora',
    noDriverBody:
      'Todos los conductores cercanos están ocupados. Intenta de nuevo en unos minutos.',
    retry: 'Reintentar',
    retryFailedTitle: 'No pudimos volver a buscar',
    retryFailedBody: 'Revisa tu conexión e inténtalo de nuevo.',
  },
  trip: {
    header: 'Tu viaje',
    notFoundTitle: 'No encontramos tu viaje',
    backHome: 'Volver al inicio',
    statusErrorTitle: 'No pudimos ver el estado de tu viaje',
    loading: 'Cargando tu viaje…',
    stepAssigned: 'Asignado',
    stepEnRoute: 'En camino',
    stepArrived: 'Llegó',
    stepInTrip: 'En viaje',
    stepsLabel: (current: string): string => `Progreso del viaje: ${current}`,
    enRouteTitle: 'Tu conductor va en camino',
    assignedTitle: 'Conductor asignado',
    arrivedTitle: 'Tu conductor llegó',
    arrivedAccent: 'llegó',
    arrivedBody: 'Te está esperando en el punto de encuentro.',
    inProgressTitle: 'Tu viaje está en curso',
    etaLabel: 'Llega en',
    etaCalculating: 'Calculando…',
    fareLabel: 'Tarifa cerrada',
    pickupLabel: 'Punto de encuentro',
    destinationLabel: 'Destino',
    callDriver: 'Llamar',
    callUnavailable: 'Número no disponible todavía',
    vehicleFallback: 'Vehículo',
    plateLabel: (plate: string): string => `Placa ${plate}`,
    freeCancellation: (remaining: string): string => `Cancelación gratis · ${remaining}`,
    cancelTrip: 'Cancelar viaje',
    cancelOfflineHint: 'Sin conexión, no se puede cancelar ahora',
    cancelledFree: 'Cancelaste sin costo.',
    cancelledRecorded: 'Viaje cancelado · quedó registrado.',
    completedTitle: '¡Viaje completado!',
    completedBody: 'Pagaste en efectivo al conductor.',
    completedAction: 'Volver al inicio',
    noShowTitle: 'No pudimos completar tu viaje',
    noShowBody:
      'El conductor no te encontró en el punto de encuentro. Puedes solicitar un nuevo viaje cuando quieras.',
    noShowAction: 'Pedir un nuevo viaje',
    cancelledByDriverTitle: 'El conductor canceló este viaje',
    cancelledByDriverBody: 'Puedes solicitar uno nuevo; te asignaremos otro conductor disponible.',
    cancelledByDriverAction: 'Pedir un nuevo viaje',
    cancelledByYouTitle: 'Cancelaste este viaje',
    cancelledByYouBody: 'Viaje cancelado · quedó registrado.',
    cancelledByYouAction: 'Volver al inicio',
  },
  cancelSheet: {
    title: '¿Cancelar viaje?',
    free: 'Gratis',
    freeBody: '· aún estás dentro del tiempo de cancelación gratuita.',
    lateBodyPrefix: 'Ya pasó el tiempo de cancelación gratuita. Quedará',
    lateEmphasis: 'registrada como cancelación tardía',
    confirm: 'Sí, cancelar',
    cancelling: 'Cancelando…',
    keep: 'Seguir esperando',
  },
  coverage: {
    title: 'Tu ubicación actual está fuera de la zona de cobertura de Yarumal.',
    action: CAN_PIN_DROP ? 'Ajustar ubicación en el mapa' : 'Elegir otro punto',
  },
  locationConsent: {
    understood: 'Entendido',
    accept: 'Acepto, usar mi ubicación',
    notNow: 'Ahora no, marcaré el punto',
    fullPolicy: 'Ver política completa',
    fullPolicyHint: 'Abre el navegador',
    saving: 'Guardando…',
    saveError: 'No pudimos guardar tu aceptación. Revisa tu conexión e inténtalo de nuevo.',
  },
  privacy: {
    header: 'Privacidad de mi ubicación',
    statusAnnounce: (badge: string): string => `Estado: ${badge}`,
    grantedBadge: 'Usando tu ubicación',
    grantedBody: (date: string): string => `Aceptaste el aviso el ${date}.`,
    versionLine: (version: string): string => `Versión del aviso: ${version}`,
    updatedBadge: 'Aviso nuevo',
    updatedBody: 'Cambiamos el aviso. Léelo y acéptalo para seguir.',
    updatedAction: 'Leer y aceptar',
    revokedBadge: 'Sin usar',
    revokedBody: (date: string): string => `Dejaste de usar tu ubicación el ${date}.`,
    revokedAction: 'Usar mi ubicación',
    noneBadge: 'Sin aceptar',
    noneBody: 'Todavía no aceptaste el aviso de ubicación.',
    noneAction: 'Leer el aviso',
    readNotice: 'Leer el aviso completo',
    revokeLink: 'Dejar de usar mi ubicación',
    rights: (email: string): string => `¿Quieres ejercer tus derechos? Escríbenos a ${email}.`,
    emailAction: 'Escribir al correo',
    emailHint: 'Abre tu correo',
    loadErrorTitle: 'No pudimos consultar tu autorización.',
    loadErrorBody: 'Inténtalo de nuevo.',
    offlineTitle: 'Sin conexión: no podemos mostrar tu estado ahora.',
    offlineHint: 'Sin conexión, esta acción no está disponible',
    revokeTitle: '¿Dejar de usar tu ubicación?',
    revokeActiveTripLine: 'Tu viaje en curso sigue igual.',
    revokeLines: [
      'Dejaremos de leer el GPS de tu teléfono.',
      'Marcarás tu punto de recogida en el mapa.',
      `Tus viajes anteriores no se borran por esto: sus coordenadas exactas se eliminan a los ${TRIP_COORDINATES_RETENTION_DAYS} días. Si quieres que se eliminen antes, escríbenos a ${DATA_CONTROLLER.privacy_email}.`,
    ],
    revokeConfirm: 'Dejar de usar mi ubicación',
    revoking: 'Guardando tu decisión…',
    openSettings: 'Abrir ajustes del teléfono',
    revokeOffline:
      'Sin conexión: todavía no registramos tu decisión. Mientras tanto no usaremos tu GPS.',
    revokeError: 'No pudimos guardar tu decisión. Inténtalo de nuevo.',
    retry: 'Reintentar',
    retryNow: 'Reintentar ahora',
    revokedToast: 'Listo. Ya no usaremos tu ubicación.',
    grantedToast: 'Listo. Guardamos tu aceptación.',
  },
  activeTrip: {
    checking: 'Revisando si tienes un viaje en curso…',
    errorTitle: 'No pudimos revisar si tienes un viaje en curso',
    errorBody: 'Sin esa revisión no sabemos si tienes un viaje abierto. Inténtalo de nuevo.',
    offlineTitle: 'Sin conexión',
    offlineBody: 'Necesitamos internet para ver si tienes un viaje en curso.',
    continueHome: 'Seguir al inicio',
    cardTitle: 'Tienes un viaje en curso',
    cardAction: 'Ver mi viaje',
    routeSummary: (origin: string, destination: string): string => `${origin} → ${destination}`,
    announce: (state: string): string => `Tienes un viaje en curso: ${state}`,
    conflictTitle: 'Ya tienes un viaje en curso',
    conflictBody: 'Para pedir otro, primero termina o cancela el que tienes.',
    opening: 'Abriendo tu viaje…',
    close: 'Cerrar',
    retry: 'Reintentar',
    ended: 'Tu viaje ya terminó. Puedes pedir otro.',
    openError: 'No pudimos abrir tu viaje.',
    openOffline: 'Sin conexión. Reintenta cuando vuelva la señal.',
  },
} as const;
