import { formatCOP } from '@voyyaa/ui-mobile';
import { FREE_CANCELLATION_WINDOW_MIN } from '../constants/parameters';
import { CAN_PIN_DROP } from '../constants/platform';

export const passengerCopy = {
  auth: {
    heroTitle: 'Tu taxi, sin llamar a nadie.',
    heroAccent: 'sin llamar a nadie.',
    phoneLabel: 'Número de celular',
    phonePlaceholder: '300 123 4567',
    phoneIntro: 'Te enviaremos un código por SMS para confirmar tu número.',
    phoneInvalid: 'Ese número no parece válido. Verifica que sean 10 dígitos de un celular.',
    sendCode: 'Enviar código',
    sending: 'Enviando…',
    offlineSend: 'Sin conexión · no se puede enviar el código ahora.',
    offlineSendHint: 'Sin conexión, no se puede enviar el código ahora',
    rateLimitTitle: 'Ya pediste varios códigos',
    rateLimitWait: (remaining: string): string =>
      `Por seguridad, espera ${remaining} antes de solicitar uno nuevo.`,
    rateLimitWaitUnknown: 'Espera unos minutos antes de intentar de nuevo.',
    otpHeader: 'Verificación',
    otpSentTo: 'Enviamos un código de 4 dígitos a',
    otpAnnounce: (maskedPhone: string): string =>
      `Código enviado a ${maskedPhone}. Ingresa los 4 dígitos.`,
    otpVerifying: 'Verificando código…',
    otpVerifyingAnnounce: 'Verificando código.',
    otpIncorrect: 'Código incorrecto. Inténtalo de nuevo.',
    otpExpired: 'Este código venció. Solicita uno nuevo.',
    otpOffline: 'Sin conexión · no pudimos verificar tu código.',
    otpOfflineAnnounce: 'Sin conexión, no pudimos verificar tu código.',
    otpSuccess: 'Código verificado.',
    otpRetry: 'Reintentar',
    otpResend: 'Reenviar código',
    otpResending: 'Reenviando…',
    otpResendIn: (seconds: number): string => `Reenviar código en ${seconds} s`,
    otpResendAvailable: 'Ya puedes reenviar el código.',
    otpResent: 'Código reenviado.',
    otpRateLimited: (remaining: string): string =>
      `Ya pediste varios códigos · espera ${remaining} antes de pedir otro.`,
    otpRateLimitedUnknown: 'Ya pediste varios códigos · espera unos minutos antes de pedir otro.',
  },
  home: {
    whereTo: '¿A dónde vas?',
    whereToHint: 'Toca para escribir tu destino',
    whereToLabel: '¿A dónde vas? Toca para escribir tu destino',
    placesTitle: 'Lugares de Yarumal',
    originLabel: 'Te recogemos en',
    changeOrigin: 'Cambiar',
    locating: 'Buscando tu ubicación…',
    noOriginTitle: 'No tenemos tu ubicación',
    noOriginBody: CAN_PIN_DROP
      ? 'Márcala en el mapa o vuelve a intentarlo para poder pedir tu taxi.'
      : 'Elige un lugar conocido o vuelve a intentarlo para poder pedir tu taxi.',
    useMyLocation: 'Usar mi ubicación',
    coverageErrorTitle: 'No pudimos verificar tu zona',
    coverageErrorBody: 'Puedes seguir e intentarlo; te avisaremos si tu viaje no se puede cotizar.',
    offlineNote: 'Sin conexión · algunas acciones no estarán disponibles.',
  },
  destination: {
    header: 'Tu viaje',
    noOriginTitle: 'Aún no tienes un punto de partida',
    noOriginBody: CAN_PIN_DROP
      ? 'Márcalo en el mapa o elige un lugar conocido.'
      : 'Elige un lugar conocido o usa tu ubicación.',
    useMyLocation: 'Usar mi ubicación',
    changeOrigin: 'Cambiar',
    originLabel: 'Origen',
    destinationLabel: 'Destino',
    destinationPlaceholder: 'Escribe tu destino…',
    searchLabel: 'Buscar destino',
    searchPlaceholder: 'Buscar dirección, sitio o referencia',
    placesTitle: 'Lugares de Yarumal',
    emptyTitle: 'No encontramos ese lugar',
    emptyBody: CAN_PIN_DROP ? 'Márcalo en el mapa.' : 'Prueba con otro nombre.',
    pendingLocation: CAN_PIN_DROP
      ? 'Ubicación pendiente de confirmar · márcalo en el mapa'
      : 'Ubicación pendiente de confirmar',
    pendingLabel: (title: string): string =>
      CAN_PIN_DROP
        ? `${title}, ubicación pendiente de confirmar, márcalo en el mapa`
        : `${title}, ubicación pendiente de confirmar`,
    pendingBadge: 'Pendiente',
    pinPoint: 'Punto marcado en el mapa',
    useAsOrigin: 'Usar este punto como origen',
    useAsDestination: 'Usar este punto como destino',
    verifying: 'Verificando…',
    quoting: 'Cotizando…',
    outOfCoverageTitle: 'Fuera de cobertura',
    outOfCoverage: (target: 'origin' | 'destination'): string =>
      target === 'origin'
        ? 'Ese punto de partida está fuera de la zona donde operamos en Yarumal por ahora.'
        : 'Ese destino está fuera de la zona donde operamos en Yarumal por ahora.',
    offlineQuote: 'Sin conexión · no se puede cotizar un destino ahora.',
    quoteErrorTitle: 'No pudimos cotizar tu viaje',
    quoteErrorBody: 'Inténtalo de nuevo en un momento.',
    retry: 'Reintentar',
  },
  confirm: {
    header: 'Confirmar viaje',
    origin: 'Origen',
    destination: 'Destino',
    references: 'Referencias (opcional)',
    pickupReferenceLabel: '¿Alguna referencia para que te encuentren?',
    pickupReferenceAccessibility: 'Referencia para tu punto de recogida, opcional',
    dropoffReferenceLabel: 'Referencia del destino',
    dropoffReferenceAccessibility: 'Referencia para tu destino, opcional',
    fareTitle: 'Tarifa',
    fareClosed: 'Tarifa cerrada · pagas en efectivo al terminar',
    freeCancellation: `Cancelación gratis hasta ${FREE_CANCELLATION_WINDOW_MIN} min después de asignar.`,
    requestTrip: (total: number): string => `Solicitar viaje · ${formatCOP(total)}`,
    requesting: 'Solicitando…',
    requote: 'La tarifa cambió, recotizando…',
    activeTripTitle: 'Ya tienes un viaje activo',
    activeTripBody: 'Termina o cancela ese viaje antes de pedir otro.',
    activeTripAction: 'Ver mi viaje',
    createErrorTitle: 'No pudimos crear tu solicitud',
    createErrorBody: 'Inténtalo de nuevo en un momento.',
    offlineRequest: 'Sin conexión · no se puede solicitar el viaje ahora.',
    offlineRequestHint: 'Sin conexión, no se puede solicitar ahora',
  },
  searching: {
    eyebrow: 'Tu viaje',
    title: 'Buscando tu viaje…',
    matchedTitle: 'Conductor asignado',
    body: 'Estamos contactando a los conductores cercanos.',
    prolongedBody: 'Seguimos buscando el conductor más cercano…',
    matchedBody: 'Te mostramos sus datos ahora.',
    elapsed: (mmss: string): string => `hace ${mmss}`,
    cash: 'Efectivo · tarifa cerrada',
    cancel: 'Cancelar',
    cancelling: 'Cancelando…',
    cancelOfflineHint: 'Sin conexión, no se puede cancelar ahora',
    cancelled: 'Solicitud cancelada.',
    notFoundTitle: 'No encontramos tu solicitud',
    backHome: 'Volver al inicio',
    statusErrorTitle: 'No pudimos ver el estado de tu viaje',
    noDriverTitle: 'No hay taxis disponibles ahora',
    noDriverBody:
      'Todos los conductores cercanos están ocupados. Intenta de nuevo en unos minutos.',
    retry: 'Reintentar',
    retryFailedTitle: 'No pudimos volver a buscar',
    retryFailedBody: 'Revisa tu conexión e inténtalo de nuevo.',
  },
  trip: {
    header: 'Tu viaje',
    notFoundTitle: 'No encontramos tu viaje',
    backHome: 'Volver al inicio',
    statusErrorTitle: 'No pudimos ver el estado de tu viaje',
    loading: 'Cargando tu viaje…',
    stepAssigned: 'Asignado',
    stepEnRoute: 'En camino',
    stepArrived: 'Llegó',
    stepInTrip: 'En viaje',
    stepsLabel: (current: string): string => `Progreso del viaje: ${current}`,
    enRouteTitle: 'Tu conductor va en camino',
    assignedTitle: 'Conductor asignado',
    arrivedTitle: 'Tu conductor llegó',
    arrivedAccent: 'llegó',
    arrivedBody: 'Te está esperando en el punto de encuentro.',
    inProgressTitle: 'Tu viaje está en curso',
    etaLabel: 'Llega en',
    etaCalculating: 'Calculando…',
    fareLabel: 'Tarifa cerrada',
    pickupLabel: 'Punto de encuentro',
    destinationLabel: 'Destino',
    callDriver: 'Llamar',
    callUnavailable: 'Número no disponible todavía',
    vehicleFallback: 'Vehículo',
    plateLabel: (plate: string): string => `Placa ${plate}`,
    freeCancellation: (remaining: string): string => `Cancelación gratis · ${remaining}`,
    cancelTrip: 'Cancelar viaje',
    cancelOfflineHint: 'Sin conexión, no se puede cancelar ahora',
    cancelledFree: 'Cancelaste sin costo.',
    cancelledRecorded: 'Viaje cancelado · quedó registrado.',
    completedTitle: '¡Viaje completado!',
    completedBody: 'Pagaste en efectivo al conductor.',
    completedAction: 'Volver al inicio',
    noShowTitle: 'No pudimos completar tu viaje',
    noShowBody:
      'El conductor no te encontró en el punto de encuentro. Puedes solicitar un nuevo viaje cuando quieras.',
    noShowAction: 'Pedir un nuevo viaje',
    cancelledByDriverTitle: 'El conductor canceló este viaje',
    cancelledByDriverBody: 'Puedes solicitar uno nuevo; te asignaremos otro conductor disponible.',
    cancelledByDriverAction: 'Pedir un nuevo viaje',
    cancelledByYouTitle: 'Cancelaste este viaje',
    cancelledByYouBody: 'Viaje cancelado · quedó registrado.',
    cancelledByYouAction: 'Volver al inicio',
  },
  cancelSheet: {
    title: '¿Cancelar viaje?',
    free: 'Gratis',
    freeBody: `· aún estás dentro de los ${FREE_CANCELLATION_WINDOW_MIN} minutos.`,
    lateBodyPrefix: `Pasaron más de ${FREE_CANCELLATION_WINDOW_MIN} minutos desde la asignación. Quedará`,
    lateEmphasis: 'registrada como cancelación tardía',
    confirm: 'Sí, cancelar',
    cancelling: 'Cancelando…',
    keep: 'Seguir esperando',
  },
  coverage: {
    title: 'Tu ubicación actual está fuera de la zona de cobertura de Yarumal.',
    action: CAN_PIN_DROP ? 'Ajustar ubicación en el mapa' : 'Elegir otro punto',
  },
  locationConsent: {
    title: 'Antes de mostrar tu ubicación',
    understood: 'Entendido',
    continue: 'Continuar',
    notNow: 'Ahora no',
    rows: [
      { label: 'Qué usamos', value: 'Tu ubicación aproximada, al abrir la app.' },
      {
        label: 'Para qué',
        value:
          'Para confirmar que estás en zona de cobertura y ubicarte en el mapa al pedir tu taxi.',
      },
      { label: 'Cuánto la guardamos', value: 'Queda asociada al historial de tus viajes.' },
      {
        label: 'Si dices que no',
        value:
          'Igual puedes pedir tu taxi: marcas el punto de recogida en el mapa. Puedes cambiar de opinión cuando quieras, desde los ajustes de tu teléfono.',
      },
    ],
  },
} as const;
