export const ACCEPTANCE_TIMEOUT_FALLBACK_SEC = 15;

export const SEARCH_RADIUS_FALLBACK_KM = 2;

export const COUNTDOWN_WARN_THRESHOLD_SEC = 5;

export const NEARBY_OFFERS_POLL_MS = 4000;

export const ACTION_RESPONSE_TIMEOUT_MS = 8000;
