export const uiCopy = {
  loading: 'Cargando…',
  updating: 'Actualizando',
  stillLoading: 'Sigue cargando…',
  loadingTakesLonger: 'Esto está tardando más de lo normal',
  cancel: 'Cancelar',
  close: 'Cerrar',
  back: 'Volver',
  retry: 'Reintentar',
  retryNow: 'Reintentar ahora',
  offlineRetrying: 'Sin conexión · reintentando…',
  connectionRestored: 'Conexión restablecida',
  updatedAgo: 'Actualizado hace',
  offlineTitle: 'Sin conexión',
  offlineBody: 'Revisa tu señal e inténtalo de nuevo.',
  show: 'Mostrar',
  hide: 'Ocultar',
  bootLabel: 'Abriendo VoyYa',
  accountTitle: 'Tu cuenta',
  accountOpen: 'Mi cuenta',
  privacyLink: 'Privacidad de mi ubicación',
  logout: 'Cerrar sesión',
  logoutConfirmTitle: '¿Cerrar sesión en este teléfono?',
  logoutConfirmBody: 'Tendrás que ingresar de nuevo para pedir o recibir viajes.',
  loggingOut: 'Cerrando sesión…',
  otpSuccess: 'Código verificado',
  seconds: 'seg',
  secondsToRespond: 'segundos para responder',
  accepted: 'Solicitud aceptada',
  timeUp: 'Tiempo agotado',
  routeOrigin: 'Origen',
  routeDestination: 'Destino',
} as const;
